version: "3.7"
services:
  db:
    image: amazon/dynamodb-local:latest
    container_name: dynamodb
    ports:
      - "8010:8000"

  dynamodb-admin:
    image: aaronshaf/dynamodb-admin
    ports:
      - "8011:8001"
    environment:
      DYNAMO_ENDPOINT: "http://dynamodb:8000"
      AWS_REGION: "us-east-1"
      AWS_ACCESS_KEY_ID: local
      AWS_SECRET_ACCESS_KEY: local
    depends_on:
      - db
